"""empty message

Revision ID: 078043606b0c
Revises: 
Create Date: 2018-05-23 00:15:32.536593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078043606b0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asks', sa.Column('is_answer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asks', 'is_answer')
    # ### end Alembic commands ###
