"""empty message

Revision ID: 7657d6ef8630
Revises: 
Create Date: 2018-05-24 14:08:20.053567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7657d6ef8630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'answer_rate')
    op.add_column('asks', sa.Column('answer_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asks', 'answer_rate')
    op.add_column('answers', sa.Column('answer_rate', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
